name: Bliblou

on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: Commytho V1.0
    runs-on: ubuntu-latest

    steps:
    # Checkout current project
    - name: Checkout Current Project
      uses: actions/checkout@v2
      with:
          persist-credentials: false 
          fetch-depth: 0
    # Checkout Commytho in a subdir
    - name: Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false 
          fetch-depth: 0
          ref: feat/commytho
          repository: dix/atoutscript
          path: ./atoutscript
    # Copy Commytho in working directory
    - name: Copy Commytho in working directory
      run: cp ./atoutscript/commytho/* .
    # Setup Node.js
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    # Install packages  
    - run:
        npm install
    # Launch Commytho
    - name: Launch !
      run: npm run start -- --git.email=reg.dev@am35.fr --git.username=dixdix --outputfile=tmp.txt
    # Push result
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    # Done
    - name: End
      run: echo 'And... cut!'
